# Docker compose para versión básica sin WeasyPrint
version: '3.8'

services:
  cfdi-app-basic:
    build:
      context: .
      dockerfile: Dockerfile.basic
    ports:
      - "8502:8501"
    volumes:
      - ./data:/app/data
    environment:
      - STREAMLIT_THEME_BASE=light
      - STREAMLIT_SERVER_PORT=8501
    restart: unless-stopped
    container_name: cfdi-app-basic
