version: '3.8'

services:
  cfdi-processor:
    build: .
    ports:
      - "8502:8501"
    volumes:
      - ./uploads:/tmp/uploads
      - ./output:/app/output
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    container_name: cfdi-processor-app
    networks:
      - cfdi-network

networks:
  cfdi-network:
    driver: bridge
